# environment.yaml
# Author  : Zhong, Yinjie; Stull, Sebastian
# Contact : yinjie.zhong@vanderbilt.edu; sebastian.l.stull@vanderbilt.edu

name: enzyhtp-gpt
channels:
  - anaconda
  - defaults
dependencies:
  - ca-certificates=2022.4.26
  - click=8.0.4
  - dataclasses=0.8
  - itsdangerous=2.0.1
  - jinja2=3.0.3
  - libffi=3.4.4
  - markupsafe=2.1.1
  - ncurses=6.4
  - openssl=3.0.11
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - werkzeug=2.0.3
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - python>=3.7
  - flask
  - flask-cors
  - flask-login
  - flask-sqlalchemy
  - flask-wtf
  - openai
  - dataclasses
  - libcxx
  - windows-curses
  - pymol-open-source
  - openbabel
