[uwsgi]
project=flask-server
base=/var/www

chdir=%(base)/%(project)

; How many tasks to be processed at the same time.
master = true
processes = 12
threads = 4
enable-threads = True

; Here directly use uwsgi as web server, use http.
http=0.0.0.0:8000
buffer-size=131071

; Flask app entry point.
wsgi-file=server.py
callable=app

; Set a request timeout (seconds), if a request exceeds this time, the request will be discarded.
harakiri=60

; When a request is killed by harakiri, a log will be output
harakiri-verbose=true