#! python3
# -*- encoding: utf-8 -*-
'''
@File    :   models.py
@Created :   2023/10/21 21:29
@Author  :   Zhong, Yinjie
@Version :   1.0
@Contact :   yinjie.zhong@vanderbilt.edu
'''

# Here put the import lib.
from __future__ import annotations  # To enable the annotation that a staticmethod of a class returns an instance of the class.
from flask_login import UserMixin
from flask_mail import Message
from sqlalchemy import and_
from typing import Tuple
from datetime import datetime, timedelta
from requests import post
from random import choice
from string import Template
from os import getcwd, path

import uuid
import jwt

# Here put local imports.
from context import mongo, mail
from config import (
    MAIL_PASSWORD_RESET_HTML_TEMPLATE,
)
from services import OpenAIService

db = mongo.db

# class User(db.Model, UserMixin):
class User(UserMixin):
    """User Model: User Information.

    Attributes:
        id (str): Identity generated by UUID4.
        email (str): Email address of the user.
        password (str): Password hashed with SHA256.
        username (str): The username.
        openai_api_key (str): The user's OpenAI API Key to access OpenAI Services such as ChatGPT.
        registered_on (datetime): The time when the user is registered.
        admin (bool): The flag showing if the user is an admin.
    """
    __tablename__ = "users"
    __is_active: bool
    # id = db.Column(db.String(36), primary_key=True, unique=True)
    # email = db.Column(db.String(255), nullable=False, unique=True)
    # password = db.Column(db.String(64), nullable=False)
    # username = db.Column(db.String(64), nullable=True)
    # openai_secret_key = db.Column(db.String(64), nullable=True)
    # registered_on = db.Column(db.DateTime, nullable=False)
    # admin = db.Column(db.Boolean, nullable=False, default=False)
    # is_active = db.Column(db.Boolean, nullable=False, default=True)

    @staticmethod
    def check_username(username: str) -> bool:
        """Check if the username is legal.
        
        Args:
            username: The username to set.

        Returns:
            If the username passes the check.
        """
        username = username.replace(' ', '')
        if (len(username) >= 2):
            return True
        else:
            return False

    @staticmethod
    def __generate_password_hash(password_plaintext: str) -> str:
        """Encrypt the password with SHA256.

        Args:
            password_plaintext: Plaintext Password.
        
        Returns:
            password: Encrypted Password.
        """
        from hashlib import sha256
        password = sha256(password_plaintext.encode('utf-8')).hexdigest().lower()
        return password

    @staticmethod
    def get(id: str) -> User | None:
        """Get user instance.
        
        Args:
            id: The `id` to identify a user.
        """
        user = User.from_dict(db.users.find_one({"id": id}))
        # user = User.query.filter_by(id=id).first()
        if (user):
            return user
        else:
            return None
        
    @staticmethod
    def get_by_email(email: str) -> User | None:
        """Search for `User` instance by email.
        
        Args:
            email: User email.
        
        Returns:
            `User` instance with matched email address.
        """
        user = User.from_dict(db.users.find_one({"email": email}))
        # user = User.query.filter_by(email=email).first()
        if (user):
            return user
        else:
            return None
    
    def __init__(self, email: str, password_plaintext: str = '', username: str = '', admin: bool = False, **kwargs) -> None:
        """Initialize a new UserModel class.

        Args:
            email (str): Email address of the user.
            password_plaintext (str): Plaintext Password submitted from the user.
            username (str): The username.
            admin (bool): If this user is an admin user (Default: False).
            kwargs: Other keyword arguments.
        """
        self.email = email
        self.password = kwargs.get("password", User.__generate_password_hash(password_plaintext))
        if (self.set_username(username)):  # Do when a legal username is given.
            pass
        elif (email.count('@') > 0):    # Do when the user has no username but has a regular email address.
            self.username = email.split('@')[0]
        else:
            self.username = email       # Do when the user doesn't either provide a username or have a regular email address.
        self.admin = admin
        self.id = kwargs.get("id", str(uuid.uuid4()))
        self.registered_on = kwargs.get("registered_on", datetime.now())
        self.openai_secret_key = kwargs.get("openai_secret_key", None)
        self.is_active = kwargs.get("is_active", True)
        return
    
    def set_password(self, password: str) -> None:
        """Reset password.
        
        Args:
            self: Current instance.
            password: Password submitted from the user.
        """
        self.password = User.__generate_password_hash(password)
        return
    
    def verify_password(self, password: str) -> bool:
        """Verify password.
        
        Args:
            self: Current instance.
            password: Password submitted from the user.
        """
        is_password_identical = (self.password == User.__generate_password_hash(password))
        return is_password_identical

    def set_username(self, username: str) -> bool:
        """Set username.
        
        Args:
            username: The new username to set.

        Returns:
            If the username is set or renewed.
        """
        if (User.check_username(username)):
            self.username = username
            return True
        else:
            return False
        
    def get_id(self) -> str:
        """Get the ID of current user.
        
        Returns:
            The id of current user.
        """
        return self.id

    def get_openai_secret_key_status(self) -> Tuple[bool, int, str]:
        """Verify by sending a prompt to ChatGPT and check its response code.
        - If the OpenAI Secret Key is valid?
        - If the account has sufficient credit?        

        Returns:
            is_valid (bool): Whether the API key is valid.
            status_code (int): The HTTP status code from the API response.
            response_content (str): The response message to describe the status.
        """
        service = OpenAIService(self.openai_secret_key, max_tokens=30)
        return service.ask_gpt("Please say an emotional welcome speech, no less than 8 words, to welcome me to ChatGPT, and add punctuation at the end.")

    @property
    def is_active(self):
        return self.__is_active

    @is_active.setter
    def is_active(self, value):
        self.__is_active = value

    @property
    def has_openai_secret_key(self) -> bool:
        '''Does the user have OpenAI Secret Key?'''
        if self.openai_secret_key:
            return True
        else:
            return False
    
    def as_dict(self) -> dict:
        """Serialize the current instance to a dictionary."""
        dict_data = self.__dict__
        return dict_data
    
    @staticmethod
    def from_dict(user_dict: dict | None) -> User:
        """Build an user instance from a dict.
        
        Args:
            user_dict (dict): A dictionary containing data of the user.
        """
        if (user_dict is None):
            return None
        user = User(**user_dict)
        return user
        
    def __repr__(self):
        return f"User('{self.id}', '{self.username}', '{self.email}')"

class OAuthUser():
    """User from Social Login.
    
    Attributes:
        id (str): OAuth Account ID generated by UUID4.
        email (str): Email address of the oauth user.
        oauth_vendor (str): OAuth Vendor, e.g. Google, Microsoft, etc.
        registered_on (datetime): The time when the user is registered.
        user_id: The user ID (of `users` table) to which it is bound.

    """
    __tablename__ = "oauth_users"
    # id = db.Column(db.String(36), primary_key=True, unique=True)
    # email = db.Column(db.String(255), nullable=False, unique=True)
    # oauth_vendor = db.Column(db.String(64), nullable=False)
    # registered_on = db.Column(db.DateTime, nullable=False)
    # user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=True)
    # user: User = db.relationship('User', backref=db.backref('oauth_users'))

    @staticmethod
    def camel_case_oauth_vendor(oauth_vendor: str) -> str:
        """Convert the name of OAuth Vendor to camel case  
        (e.g. GOOGLE -> Google, microsoft -> Microsoft).
        
        Args:
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
        
        Returns:
            Camel case OAuth vendor name.
        """
        if (len(oauth_vendor) <= 1):
            return oauth_vendor.upper()
        else:
            return f'{oauth_vendor[0].upper()}{oauth_vendor[1:].lower()}'

    @staticmethod
    def get_by_email_and_vendor(email: str, oauth_vendor: str) -> OAuthUser | None:
        """Search for `OAuthUser` instance by email and vendor.
        
        Args:
            email: User email.
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
        
        Returns:
            `OAuthUser` instance with matched email address and OAuth vendor.
        """
        email = email.lower()
        oauth_vendor = OAuthUser.camel_case_oauth_vendor(oauth_vendor)
        oauth_user = OAuthUser.from_dict(db.oauth_users.find_one({"email": email, "oauth_vendor": oauth_vendor}))
        # oauth_user = OAuthUser.query.filter(OAuthUser.email==email, OAuthUser.oauth_vendor==oauth_vendor).first()
        if (oauth_user):
            return oauth_user
        else:
            return None

    def __init__(self, email: str, oauth_vendor: str, user_id: str = None, **kwargs) -> None:
        """Initialize a new UserModel class.

        Args:
            email: Email address of the oauth user.
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
            user_id: The user ID (of `users` table) to which it is bound.
            kwargs: Other keyword arguments.
        """
        self.email = email
        self.oauth_vendor = OAuthUser.camel_case_oauth_vendor(oauth_vendor)
        self.user_id = user_id
        self.id = kwargs.get("id", str(uuid.uuid4()))
        self.registered_on = kwargs.get("registered_on", datetime.now())
        return
    
    def as_dict(self):
        """Serialize the current instance to a dictionary."""
        dict_data = self.__dict__
        return dict_data
    
    @staticmethod
    def from_dict(oauth_user_dict: dict | None) -> OAuthUser:
        """Build an OAuthUser instance from a dict.
        
        Args:
            oauth_user_dict (dict): A dictionary containing data of the OAuth User.
        """
        if (oauth_user_dict is None):
            return None
        oauth_user = OAuthUser(**oauth_user_dict)
        return oauth_user

class VerificationCode():
    """Verification Code Model.

    Store verification code for resetting password.
    
    Attributes:
        id (str): Identity generated by UUID4.
        verification_code (str): Verification code.
        created_on (datetime): The time when the verification code is created.
        is_used (bool): The flag showing if the verification code is used.
        user_id: The user ID (of `users` table) to which it is bound.
    """
    __tablename__ = "verification_codes"
    # id = db.Column(db.String(36), primary_key=True, unique=True)
    # verification_code = db.Column(db.String(15), nullable=False)
    # creation_time = db.Column(db.DateTime, nullable=False)
    # expiration_time = db.Column(db.DateTime, nullable=False)
    # is_used = db.Column(db.Boolean, nullable=False, default=False)
    # user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=True)
    # user = db.relationship('User', backref=db.backref('verification_codes'))

    MAIL_SUBJECT = "Reset Your Password for EnzyHTP Web Application"

    def __init__(self, user_id: str, valid_minutes: float = 20, length: int = 6, **kwargs):
        """Initialize a new VerificationCode instance.
        
        Args:
            user_id: The user ID (of `users` table) to which it is bound.
            valid_minutes (float): The number of minutes the verification code will be valid for.
            length (int): The length of the verification code.
            kwargs: Other keyword arguments.
        """
        self.user_id = user_id
        self.creation_time = kwargs.get("creation_time", datetime.now())
        self.expiration_time = kwargs.get("expiration_time", self.creation_time + timedelta(minutes=valid_minutes))
        self.is_used = kwargs.get("is_used", False)
        self.verification_code = kwargs.get("verification_code", self.__class__.generate_verification_code(length))
        self.id = kwargs.get("id", str(uuid.uuid4()))
        return

    def send_email(self) -> bool:
        """Send email conveying verification code for password reset.
        
        Returns:
            If the email is successfully sent.
        """
        user = User.get(self.user_id)

        email_html = Template(MAIL_PASSWORD_RESET_HTML_TEMPLATE).safe_substitute({
            "username": user.username,
            "email": user.email,
            "verification_code": self.verification_code,
            "valid_mins": int((self.expiration_time - self.creation_time).total_seconds() / 60)
        })
        try:
            email_obj = Message(subject=self.__class__.MAIL_SUBJECT, html=email_html)
            email_obj.add_recipient(user.email)
            mail.send(email_obj)
            return True
        except Exception as exc:
            print(exc)
            return False

    @staticmethod
    def get_by_user_and_code(user: User, verification_code: str) -> VerificationCode | None:
        """Search for `User` instance by email.
        
        Args:
            user (User): User instance.
            verification_code (str): Verification code.
        
        Returns:
            `VerificationCode` instance with matched email address and verification_code.
        """
        code_record = VerificationCode.from_dict(db.verification_codes.find_one({"user_id": user.id, "verification_code": verification_code}))
        # code_record: VerificationCode = VerificationCode.query.filter(and_(VerificationCode.user_id == user.id, VerificationCode.verification_code == verification_code)).first()
        if (code_record):
            return code_record
        else:
            return None
        
    @staticmethod
    def clean_expired_records() -> None:
        """Clean up verification code records that have existed for more than a day."""
        current_time = datetime.now()
        time_checkpoint = current_time - timedelta(days=1)
        # VerificationCode.query.filter(VerificationCode.creation_time < time_checkpoint).delete()
        db.verification_codes.delete_many({"creation_time": {"lte": time_checkpoint}})
        # db.session.commit()

    @staticmethod
    def generate_verification_code(length: int = 6) -> str:
        """Generate a verification, a combination of alphabets and numbers, with given length.
        
        Args:
            length (int, optional): The length of the verification code.
        """
        char_list = list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890")

        verification_code = str()
        for i in range(length):
            random_char = choice(char_list)
            verification_code += random_char
            continue
        return verification_code
    
    def as_dict(self):
        """Serialize the current instance to a dictionary."""
        dict_data = self.__dict__
        return dict_data
    
    @staticmethod
    def from_dict(verification_code_dict: dict | None) -> VerificationCode:
        """Build an VerificationCode instance from a dict.
        
        Args:
            verification_code (dict): A dictionary containing data of the Verification Code record.
        """
        if (verification_code_dict is None):
            return None
        verification_code = VerificationCode(**verification_code_dict)
        return verification_code

# Reference: https://www.askpython.com/python-modules/flask/flask-user-authentication