#! python3
# -*- encoding: utf-8 -*-
'''
@File    :   models.py
@Created :   2023/10/21 21:29
@Author  :   Zhong, Yinjie
@Version :   1.0
@Contact :   yinjie.zhong@vanderbilt.edu
'''

# Here put the import lib.
from __future__ import annotations  # To enable the annotation that a staticmethod of a class returns an instance of the class.
from flask_login import UserMixin
from flask_mail import Message
from sqlalchemy import and_
import uuid
from typing import Tuple
from datetime import datetime, timedelta
from requests import post
from random import choice
from string import Template
from os import getcwd, path

from context import db
from server import mail
from settings import (
    OPENAI_API_URI,

    MAIL_PASSWORD_RESET_HTML_TEMPLATE,
)

class User(db.Model, UserMixin):
    """User Model: User Information.

    Attributes:
        id (str): Identity generated by UUID4.
        email (str): Email address of the user.
        password (str): Password hashed with SHA256.
        username (str): The username.
        openai_api_key (str): The user's OpenAI API Key to access OpenAI Services such as ChatGPT.
        registered_on (datetime): The time when the user is registered.
        admin (bool): The flag showing if the user is an admin.
    """
    __tablename__ = "users"
    id = db.Column(db.String(36), primary_key=True, unique=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(64), nullable=False)
    username = db.Column(db.String(64), nullable=True)
    openai_secret_key = db.Column(db.String(64), nullable=True)
    registered_on = db.Column(db.DateTime, nullable=False)
    admin = db.Column(db.Boolean, nullable=False, default=False)
    is_active = db.Column(db.Boolean, nullable=False, default=True)

    @staticmethod
    def check_username(username: str) -> bool:
        """Check if the username is legal.
        
        Args:
            username: The username to set.

        Returns:
            If the username passes the check.
        """
        username = username.replace(' ', '')
        if (len(username) >= 2):
            return True
        else:
            return False

    @staticmethod
    def __generate_password_hash(password_plaintext: str) -> str:
        """Encrypt the password with SHA256.

        Args:
            password_plaintext: Plaintext Password.
        
        Returns:
            password: Encrypted Password.
        """
        from hashlib import sha256
        password = sha256(password_plaintext.encode('utf-8')).hexdigest().lower()
        return password

    @staticmethod
    def get(id: str) -> User | None:
        """Get user instance.
        
        Args:
            id: The `id` to identify a user.
        """
        user = User.query.filter_by(id=id).first()
        if (user):
            return user
        else:
            return None
        
    @staticmethod
    def get_by_email(email: str) -> User | None:
        """Search for `User` instance by email.
        
        Args:
            email: User email.
        
        Returns:
            `User` instance with matched email address.
        """
        user = User.query.filter_by(email=email).first()
        if (user):
            return user
        else:
            return None
    
    def __init__(self, email: str, password: str, username: str = '', admin: bool = False) -> None:
        """Initialize a new UserModel class.

        Args:
            email: Email address of the user.
            password: Password submitted from the user.
            username: The username.
            admin: If this user is an admin user (Default: False).
        """
        self.id = str(uuid.uuid4())
        self.email = email
        self.password = User.__generate_password_hash(password)
        if (User.check_username(username)):  # Do when a legal username is given.
            self.username = username
        elif (email.count('@') > 0):    # Do when the user has no username but has a regular email address.
            self.username = email.split('@')[0]
        else:
            self.username = email       # Do when the user doesn't either provide a username or have a regular email address.
        self.registered_on = datetime.utcnow()
        self.admin = admin
        return
    
    def set_password(self, password: str) -> None:
        """Reset password.
        
        Args:
            self: Current instance.
            password: Password submitted from the user.
        """
        self.password = User.__generate_password_hash(password)
        return
    
    def verify_password(self, password: str) -> bool:
        """Verify password.
        
        Args:
            self: Current instance.
            password: Password submitted from the user.
        """
        is_password_identical = (self.password == User.__generate_password_hash(password))
        return is_password_identical

    def set_username(self, username: str) -> bool:
        """Set username.
        
        Args:
            self: Current instance.
            username: The new username to set.

        Returns:
            If the username is set or renewed.
        """
        if (User.check_username(username)):
            self.username = username
            return True
        else:
            return False
        
    def get_id(self) -> str:
        """Get the ID of current user.
        
        Returns:
            The id of current user.
        """
        return self.id

    def get_openai_secret_key_status(self) -> Tuple[bool, int, str]:
        """Verify by sending a prompt to ChatGPT and check its response code.
        - If the OpenAI Secret Key is valid?
        - If the account has sufficient credit?        

        Returns:
            is_valid (bool): Is the user's key valid?
            status_code (int): The status code from OpenAI.
            response_msg (str): The response message to describe the status.
        """
        valid_key_response_code_list = [200, 400, 429]
        response_msg_dict = {
            200: "Your OpenAI Secret Key is valid and your account balance is sufficient.",
            429: "You exceeded your current OpenAI API quota, please check your plan and billing details.",
            400: "Your OpenAI Secret Key is valid, but you sent a bad request.",
            401: "Invalid OpenAI Secret Key.",
            500: "OpenAI Internal Server Error. Unable to verify."
        }
        is_valid = False
        status_code = 500

        if self.openai_secret_key:
            is_valid = False

            headers = {
                'Authorization': f'Bearer {self.openai_secret_key}',
                'Content-Type': 'application/json',
            }
            url = OPENAI_API_URI
            request_body = {
                "model": "gpt-3.5-turbo",
                "max_tokens": 30,
                "messages": [
                    {
                        "role": "user",
                        "content": "Please say an emotional welcome speech, no less than 8 words, to welcome me to ChatGPT, and add punctuation at the end."
                    }
                ]
            }
            try:
                response = post(url, headers=headers, json=request_body)
                status_code = response.status_code
                if status_code in valid_key_response_code_list:
                    is_valid = True
                    if status_code == 200:
                        response_json = response.json()
                        response_msg_dict[200] = response_json['choices'][0]['message']['content']
                else:
                    pass
            except:
                pass
        else:
            response_msg_dict[500] = "OpenAI Secret Key does not exist."
        return is_valid, status_code, response_msg_dict[status_code]

    @property
    def has_openai_secret_key(self) -> bool:
        '''Does the user have OpenAI Secret Key?'''
        if self.openai_secret_key:
            return True
        else:
            return False

class OAuthUser(db.Model):
    """User from Social Login.
    
    Attributes:
        id (str): OAuth Account ID generated by UUID4.
        email (str): Email address of the oauth user.
        oauth_vendor (str): OAuth Vendor, e.g. Google, Microsoft, etc.
        registered_on (datetime): The time when the user is registered.
        user_id: The user ID (of `users` table) to which it is bound.

    """
    __tablename__ = "oauth_users"
    id = db.Column(db.String(36), primary_key=True, unique=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    oauth_vendor = db.Column(db.String(64), nullable=False)
    registered_on = db.Column(db.DateTime, nullable=False)
    user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=True)
    user = db.relationship('User', backref=db.backref('oauth_users'))

    @staticmethod
    def camel_case_oauth_vendor(oauth_vendor: str) -> str:
        """Convert the name of OAuth Vendor to camel case  
        (e.g. GOOGLE -> Google, microsoft -> Microsoft).
        
        Args:
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
        
        Returns:
            Camel case OAuth vendor name.
        """
        if (len(oauth_vendor) <= 1):
            return oauth_vendor.upper()
        else:
            return f'{oauth_vendor[0].upper()}{oauth_vendor[1:].lower()}'

    @staticmethod
    def get_by_email_and_vendor(email: str, oauth_vendor: str) -> OAuthUser | None:
        """Search for `OAuthUser` instance by email and vendor.
        
        Args:
            email: User email.
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
        
        Returns:
            `OAuthUser` instance with matched email address and OAuth vendor.
        """
        email = email.lower()
        oauth_vendor = OAuthUser.camel_case_oauth_vendor(oauth_vendor)

        oauth_user = OAuthUser.query.filter(OAuthUser.email==email, OAuthUser.oauth_vendor==oauth_vendor).first()
        if (oauth_user):
            return oauth_user
        else:
            return None

    def __init__(self, email: str, oauth_vendor: str, user_id: str = None) -> None:
        """Initialize a new UserModel class.

        Args:
            email: Email address of the oauth user.
            oauth_vendor: OAuth Vendor, e.g. Google, Microsoft, etc.
            user_id: The user ID (of `users` table) to which it is bound.
        """
        self.id = str(uuid.uuid4())
        self.email = email
        self.oauth_vendor = OAuthUser.camel_case_oauth_vendor(oauth_vendor)
        self.registered_on = datetime.utcnow()
        self.user_id = user_id
        self.user = User.get(user_id)
        return

class VerificationCode(db.Model):
    """Verification Code Model.

    Store verification code for resetting password.
    
    Attributes:
        id (str): Identity generated by UUID4.
        verification_code (str): Verification code.
        created_on (datetime): The time when the verification code is created.
        is_used (bool): The flag showing if the verification code is used.
        user_id: The user ID (of `users` table) to which it is bound.
    """
    __tablename__ = "verification_codes"
    id = db.Column(db.String(36), primary_key=True, unique=True)
    verification_code = db.Column(db.String(15), nullable=False)
    creation_time = db.Column(db.DateTime, nullable=False)
    expiration_time = db.Column(db.DateTime, nullable=False)
    is_used = db.Column(db.Boolean, nullable=False, default=False)
    user_id = db.Column(db.String(36), db.ForeignKey('users.id'), nullable=True)
    user = db.relationship('User', backref=db.backref('verification_codes'))

    MAIL_SUBJECT = "Reset Your Password for EnzyHTP Web Application"

    def __init__(self, user: User, valid_minutes: float, length: int = 6):
        """Initialize a new VerificationCode instance.
        
        Args:
            user (User): A User instance.
            valid_minutes (float): The number of minutes the verification code will be valid for.
            length (int): The length of the verification code.
        """
        self.id = str(uuid.uuid4())
        self.user = user
        self.user_id = user.id
        self.creation_time = datetime.now()
        self.expiration_time = self.creation_time + timedelta(minutes=valid_minutes)
        self.is_used = False
        self.verification_code = self.__class__.generate_verification_code(length)

    def send_email(self) -> bool:
        """Send email conveying verification code for password reset.
        
        Returns:
            If the email is successfully sent.
        """
        user = User.get(self.user_id)

        email_html = Template(MAIL_PASSWORD_RESET_HTML_TEMPLATE).safe_substitute({
            "username": user.username,
            "email": user.email,
            "verification_code": self.verification_code,
            "valid_mins": int((self.expiration_time - self.creation_time).total_seconds() / 60)
        })
        try:
            email_obj = Message(subject=self.__class__.MAIL_SUBJECT, html=email_html)
            email_obj.add_recipient(user.email)
            mail.send(email_obj)
            return True
        except Exception as exc:
            print(exc)
            return False

    @staticmethod
    def get_by_user_and_code(user: User, verification_code: str) -> VerificationCode | None:
        """Search for `User` instance by email.
        
        Args:
            user (User): User instance.
            verification_code (str): Verification code.
        
        Returns:
            `VerificationCode` instance with matched email address and verification_code.
        """
        code_record: VerificationCode = VerificationCode.query.filter(and_(VerificationCode.user_id == user.id, VerificationCode.verification_code == verification_code)).first()
        if (code_record):
            return code_record
        else:
            return None

    @staticmethod
    def generate_verification_code(length: int = 6) -> str:
        """Generate a verification, a combination of alphabets and numbers, with given length.
        
        Args:
            length (int, optional): The length of the verification code.
        """
        char_list = list("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890")

        verification_code = str()
        for i in range(length):
            random_char = choice(char_list)
            verification_code += random_char
            continue
        return verification_code


if __name__ == '__main__':
    user = User('y.z@vu', '123456')
    print(user.email)
    print(user.password)

# Reference: https://www.askpython.com/python-modules/flask/flask-user-authentication